/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { ChainProof, ChainProofInterface } from "../ChainProof";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "HashAnchored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    name: "anchor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610170806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063eecdf92714610030575b600080fd5b61004a600480360381019061004591906100d9565b61004c565b005b3373ffffffffffffffffffffffffffffffffffffffff16817fa5cbeb7570a6c7c834762f7c213557e60c453fd24203dd5f7d85864ff2738c3942604051610093919061011f565b60405180910390a350565b600080fd5b6000819050919050565b6100b6816100a3565b81146100c157600080fd5b50565b6000813590506100d3816100ad565b92915050565b6000602082840312156100ef576100ee61009e565b5b60006100fd848285016100c4565b91505092915050565b6000819050919050565b61011981610106565b82525050565b60006020820190506101346000830184610110565b9291505056fea2646970667358221220c4ae392c33ad66d51279ec1659b1c1a80dd380f6ef8b0d3d5fa1380e7bf9799464736f6c63430008140033";

type ChainProofConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ChainProofConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ChainProof__factory extends ContractFactory {
  constructor(...args: ChainProofConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ChainProof & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ChainProof__factory {
    return super.connect(runner) as ChainProof__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChainProofInterface {
    return new Interface(_abi) as ChainProofInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ChainProof {
    return new Contract(address, _abi, runner) as unknown as ChainProof;
  }
}
